import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import type { CompanyUserRole, Location } from '@stocky/types';

export interface MobileTodayMetrics { expired: number; expiring: number; lowStock: number; openCounts: number; }

export function MobileTodayScreen({ userName, userRole, location, metrics, onScan, onReceive, onCount, onOpenStock, onOpenExpiry }: { userName?: string | null; userRole: CompanyUserRole; location?: Location; metrics: MobileTodayMetrics; onScan: () => void; onReceive: () => void; onCount: () => void; onOpenStock: () => void; onOpenExpiry: () => void }) {
  const isStaff = userRole === 'staff';
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>{location?.name || 'All locations'}</Text><Text style={styles.title}>{isStaff ? 'Your tasks today' : `Good morning${userName ? `, ${userName.split(/\s+/)[0]}` : ''}`}</Text><Text style={styles.subtitle}>Simple actions for keeping stock accurate and safe.</Text><View style={styles.actions}><TouchableOpacity onPress={onScan} style={[styles.action, styles.primary]}><Text style={styles.actionIcon}>▣</Text><Text style={styles.actionTitleWhite}>Scan or search</Text><Text style={styles.actionSubWhite}>Find a product</Text></TouchableOpacity><TouchableOpacity onPress={onReceive} style={styles.action}><Text style={styles.actionIcon}>＋</Text><Text style={styles.actionTitle}>Receive stock</Text><Text style={styles.actionSub}>Record a delivery</Text></TouchableOpacity><TouchableOpacity onPress={onCount} style={styles.action}><Text style={styles.actionIcon}>✓</Text><Text style={styles.actionTitle}>Count stock</Text><Text style={styles.actionSub}>Check what is there</Text></TouchableOpacity></View><Text style={styles.section}>Needs attention</Text><View style={styles.card}><TouchableOpacity onPress={onOpenExpiry} style={styles.row}><Text style={styles.rowTitle}>Expired or expiring</Text><Text style={styles.rowValue}>{metrics.expired + metrics.expiring}</Text></TouchableOpacity><View style={styles.divider} /><TouchableOpacity onPress={onOpenStock} style={styles.row}><Text style={styles.rowTitle}>Low stock products</Text><Text style={styles.rowValue}>{metrics.lowStock}</Text></TouchableOpacity>{metrics.openCounts > 0 && <><View style={styles.divider} /><TouchableOpacity onPress={onCount} style={styles.row}><Text style={styles.rowTitle}>Counts waiting for review</Text><Text style={styles.rowValue}>{metrics.openCounts}</Text></TouchableOpacity></>}</View></ScrollView>;
}

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#F8FAFC' }, content: { padding: 18, paddingBottom: 120 }, eyebrow: { color: '#0057FF', fontSize: 11, fontWeight: '500', textTransform: 'uppercase', letterSpacing: 1 }, title: { color: '#0F172A', fontSize: 28, fontWeight: '500', marginTop: 8 }, subtitle: { color: '#64748B', fontSize: 14, marginTop: 6, lineHeight: 20 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 24 }, action: { width: '47%', minHeight: 118, backgroundColor: '#FFFFFF', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#E2E8F0' }, primary: { backgroundColor: '#0057FF', borderColor: '#0057FF' }, actionIcon: { color: '#0057FF', fontSize: 24 }, actionTitle: { color: '#0F172A', fontSize: 14, fontWeight: '500', marginTop: 17 }, actionSub: { color: '#64748B', fontSize: 11, marginTop: 4 }, actionTitleWhite: { color: '#FFFFFF', fontSize: 14, fontWeight: '500', marginTop: 17 }, actionSubWhite: { color: '#DBEAFE', fontSize: 11, marginTop: 4 }, section: { color: '#0F172A', fontSize: 16, fontWeight: '500', marginTop: 28, marginBottom: 10 }, card: { backgroundColor: '#FFFFFF', borderRadius: 16, borderWidth: 1, borderColor: '#E2E8F0', paddingHorizontal: 14 }, row: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, rowTitle: { color: '#334155', fontSize: 14 }, rowValue: { color: '#0057FF', fontSize: 17, fontWeight: '500' }, divider: { height: 1, backgroundColor: '#F1F5F9' } });
