import React, { useEffect, useState } from 'react';
import { Modal, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { supabase } from '../lib/supabase';
import type { Product, StockLot } from '@stocky/types';

export function MobileActionModal({ visible, mode, product, lot, lots = [], barcode, locationId, onClose, onSaved }: { visible: boolean; mode: 'receive' | 'count'; product?: Product; lot?: StockLot; lots?: StockLot[]; barcode?: string; locationId: string; onClose: () => void; onSaved: () => void }) {
  const [quantity, setQuantity] = useState('');
  const [expiryDate, setExpiryDate] = useState('');
  const [lotNumber, setLotNumber] = useState('');
  const [notifyDays, setNotifyDays] = useState('30');
  const [reason, setReason] = useState('');
  const [unknownName, setUnknownName] = useState('');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const expectedQuantity = product ? lots.filter((item) => item.productId === product.id && item.locationId === locationId && item.quantityOnHand > 0).reduce((sum, item) => sum + item.quantityOnHand, 0) : lot?.quantityOnHand || 0;
  useEffect(() => { if (!visible) return; setQuantity(mode === 'count' ? String(expectedQuantity) : ''); setExpiryDate(''); setLotNumber(''); setNotifyDays(String(product?.defaultExpiryNotificationDays ?? lot?.expiryNotificationDays ?? 30)); setReason(''); setUnknownName(''); setError(''); }, [expectedQuantity, lot, mode, product, visible]);
  const save = async () => { const parsed = Number(quantity); if (!locationId || !Number.isInteger(parsed) || parsed < 0 || (mode === 'receive' && parsed <= 0)) return setError(mode === 'receive' ? 'Enter a quantity greater than zero.' : 'Enter a whole number.'); if (mode === 'count' && !product) return setError('Choose a product before counting.'); if (mode === 'count' && parsed !== expectedQuantity && !reason.trim()) return setError('Add a reason for the difference.'); if (mode === 'receive' && !product && !unknownName.trim()) return setError('Enter a name for this new product.'); setSaving(true); if (mode === 'receive') { const rpcName = product ? 'receive_stock' : 'receive_unidentified_stock'; const rpcArgs = product ? { p_product_id: product.id, p_location_id: locationId, p_quantity: parsed, p_lot_number: lotNumber.trim() || null, p_expiry_date: expiryDate ? new Date(`${expiryDate}T23:59:59`).toISOString() : null, p_expiry_notification_days: expiryDate ? Number(notifyDays) : null, p_supplier_id: null, p_unit_cost: product.unitCost, p_notes: 'Received from mobile app' } : { p_barcode: barcode || null, p_product_name: unknownName.trim(), p_location_id: locationId, p_quantity: parsed, p_lot_number: lotNumber.trim() || null, p_expiry_date: expiryDate ? new Date(`${expiryDate}T23:59:59`).toISOString() : null, p_expiry_notification_days: expiryDate ? Number(notifyDays) : null, p_unit_cost: 0, p_notes: 'Received as an unidentified barcode from mobile app' }; const { error: saveError } = await supabase.rpc(rpcName, rpcArgs); setSaving(false); if (saveError) return setError(saveError.message); } else { const { data: sessionId, error: startError } = await supabase.rpc('start_stock_count', { p_location_id: locationId }); if (startError) { setSaving(false); return setError(startError.message); } const { error: submitError } = await supabase.rpc('submit_stock_count', { p_session_id: sessionId, p_lines: [{ product_id: product?.id, counted_quantity: parsed, variance_reason: reason.trim() || null }] }); setSaving(false); if (submitError) return setError(submitError.message); } onSaved(); onClose(); };
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose} transparent><View style={styles.backdrop}><View style={styles.sheet}><Text style={styles.eyebrow}>{mode === 'receive' ? 'Receive stock' : 'Count stock'}</Text><Text style={styles.title}>{product?.name || (barcode ? 'Unknown barcode' : 'Product')}</Text><Text style={styles.help}>{mode === 'receive' ? product ? 'Record a new delivery batch.' : 'This barcode is not in the catalog yet. Add a simple name and receive it now.' : `Expected ${expectedQuantity} ${product?.unitName || 'units'} at this location. A manager reviews differences.`}</Text>{mode === 'receive' && !product && <Text style={styles.label}>Product name<TextInput value={unknownName} onChangeText={setUnknownName} style={styles.input} placeholder="e.g. bottled water" /></Text>}<Text style={styles.label}>{mode === 'receive' ? 'Quantity received' : 'Physical quantity'}<TextInput keyboardType="numeric" value={quantity} onChangeText={setQuantity} style={styles.input} /></Text>{mode === 'count' && Number(quantity) !== expectedQuantity && <Text style={styles.label}>Reason for difference<TextInput value={reason} onChangeText={setReason} style={styles.input} placeholder="e.g. damaged or missing" /></Text>}{mode === 'receive' && <><Text style={styles.label}>Batch / lot<TextInput value={lotNumber} onChangeText={setLotNumber} style={styles.input} placeholder="Optional" /></Text><Text style={styles.label}>Expiry date (YYYY-MM-DD)<TextInput value={expiryDate} onChangeText={setExpiryDate} style={styles.input} placeholder="Optional" /></Text><Text style={styles.label}>Notify before (days)<TextInput keyboardType="numeric" value={notifyDays} onChangeText={setNotifyDays} style={styles.input} /></Text></>}{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.actions}><TouchableOpacity onPress={onClose} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></TouchableOpacity><TouchableOpacity onPress={save} disabled={saving} style={styles.save}><Text style={styles.saveText}>{saving ? 'Saving...' : mode === 'receive' ? 'Save receipt' : 'Submit count'}</Text></TouchableOpacity></View></View></View></Modal>;
}

const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,.4)', justifyContent: 'flex-end' }, sheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 30 }, eyebrow: { color: '#0057FF', fontSize: 11, fontWeight: '500', textTransform: 'uppercase', letterSpacing: 1 }, title: { color: '#0F172A', fontSize: 22, fontWeight: '500', marginTop: 7 }, help: { color: '#64748B', fontSize: 13, lineHeight: 19, marginTop: 5, marginBottom: 16 }, label: { color: '#334155', fontSize: 12, fontWeight: '500', marginBottom: 10 }, input: { height: 44, borderRadius: 11, borderWidth: 1, borderColor: '#E2E8F0', paddingHorizontal: 12, marginTop: 6, color: '#0F172A', fontWeight: '400' }, error: { color: '#B91C1C', backgroundColor: '#FEF2F2', padding: 10, borderRadius: 9, fontSize: 12 }, actions: { flexDirection: 'row', gap: 10, marginTop: 8 }, cancel: { flex: 1, height: 46, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', justifyContent: 'center', alignItems: 'center' }, cancelText: { color: '#334155', fontWeight: '500' }, save: { flex: 1, height: 46, borderRadius: 12, backgroundColor: '#0057FF', justifyContent: 'center', alignItems: 'center' }, saveText: { color: '#FFFFFF', fontWeight: '500' } });
