import React, { useEffect, useMemo, useState } from 'react';
import { FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import type { Location, Product, StockLot } from '@stocky/types';

export function MobileStockScreen({ products, lots, locations, selectedLocationId, mode, initialSearch = '', onScan, onReceive, onCount }: { products: Product[]; lots: StockLot[]; locations: Location[]; selectedLocationId: string; mode: 'stock' | 'expiry'; initialSearch?: string; onScan: () => void; onReceive: (product?: Product, lot?: StockLot) => void; onCount: (product?: Product, lot?: StockLot) => void }) {
  const [search, setSearch] = useState('');
  useEffect(() => { setSearch(initialSearch); }, [initialSearch]);
  const productMap = useMemo(() => new Map(products.map((product) => [product.id, product])), [products]);
  const locationMap = useMemo(() => new Map(locations.map((location) => [location.id, location.name])), [locations]);
  const rows = useMemo(() => lots.filter((lot) => lot.quantityOnHand > 0 && (selectedLocationId === 'all' || lot.locationId === selectedLocationId)).filter((lot) => { const product = productMap.get(lot.productId); const query = search.trim().toLowerCase(); const days = lot.expiryDate ? Math.ceil((new Date(lot.expiryDate).getTime() - Date.now()) / 86400000) : null; const attention = !lot.expiryDate || (days !== null && days <= (lot.expiryNotificationDays ?? 0)); return (!query || [product?.name, product?.barcode, lot.lotNumber].filter(Boolean).some((value) => String(value).toLowerCase().includes(query))) && (mode === 'stock' || attention); }).sort((a, b) => (a.expiryDate || '9999').localeCompare(b.expiryDate || '9999')), [lots, mode, productMap, search, selectedLocationId]);
  return <View style={styles.container}><View style={styles.header}><Text style={styles.title}>{mode === 'expiry' ? 'Expiring soon' : 'Stock'}</Text><Text style={styles.subtitle}>{mode === 'expiry' ? 'Decide what needs removal, return, or replacement.' : 'Search products and batches at your location.'}</Text></View><View style={styles.searchRow}><TextInput value={search} onChangeText={setSearch} placeholder="Search product or barcode" placeholderTextColor="#94A3B8" style={styles.search} /><TouchableOpacity onPress={onScan} style={styles.scan}><Text style={styles.scanText}>Scan</Text></TouchableOpacity></View>{mode === 'stock' && <View style={styles.quickRow}><TouchableOpacity onPress={() => onReceive()} style={styles.quick}><Text style={styles.quickText}>＋ Receive</Text></TouchableOpacity><TouchableOpacity onPress={() => onCount()} style={styles.quick}><Text style={styles.quickText}>✓ Count</Text></TouchableOpacity></View>}<FlatList data={rows} keyExtractor={(lot) => lot.id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>{mode === 'expiry' ? 'Nothing needs attention' : 'No stock found'}</Text><Text style={styles.emptyText}>Try another search or scan a barcode.</Text>{mode === 'stock' && <TouchableOpacity onPress={() => onReceive()} style={styles.emptyAction}><Text style={styles.emptyActionText}>Receive as a new item</Text></TouchableOpacity>}</View>} renderItem={({ item: lot }) => { const product = productMap.get(lot.productId); const days = lot.expiryDate ? Math.ceil((new Date(lot.expiryDate).getTime() - Date.now()) / 86400000) : null; const attention = days === null || days <= (lot.expiryNotificationDays ?? 0); return <View style={styles.card}><View style={styles.cardTop}><Text style={styles.product}>{product?.name || 'Unknown product'}</Text><Text style={attention ? styles.warning : styles.safe}>{days === null ? 'Expiry missing' : days < 0 ? `${Math.abs(days)}d overdue` : `${days}d left`}</Text></View><Text style={styles.meta}>{locationMap.get(lot.locationId) || 'Location'} · Batch {lot.lotNumber || 'not recorded'} · {lot.quantityOnHand} {product?.unitName || 'units'}</Text><Text style={styles.meta}>{lot.expiryDate ? `Expires ${new Date(lot.expiryDate).toLocaleDateString()}` : 'Add an expiry date when receiving'}</Text>{mode === 'stock' && product && <View style={styles.cardActions}><TouchableOpacity onPress={() => onCount(product, lot)} style={styles.cardAction}><Text style={styles.cardActionText}>Count</Text></TouchableOpacity><TouchableOpacity onPress={() => onReceive(product, lot)} style={styles.cardAction}><Text style={styles.cardActionText}>Receive</Text></TouchableOpacity></View>}</View>; }} /></View>;
}

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#F8FAFC' }, header: { padding: 18, paddingBottom: 10 }, title: { color: '#0F172A', fontSize: 27, fontWeight: '500' }, subtitle: { color: '#64748B', fontSize: 13, marginTop: 5 }, searchRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 18 }, search: { flex: 1, height: 44, borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', paddingHorizontal: 13, color: '#0F172A' }, scan: { height: 44, paddingHorizontal: 14, borderRadius: 12, backgroundColor: '#0057FF', justifyContent: 'center' }, scanText: { color: '#FFFFFF', fontWeight: '500', fontSize: 12 }, quickRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 18, marginTop: 10 }, quick: { flex: 1, height: 38, borderRadius: 10, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', justifyContent: 'center', alignItems: 'center' }, quickText: { color: '#0057FF', fontSize: 12, fontWeight: '500' }, list: { padding: 18, paddingBottom: 120 }, card: { backgroundColor: '#FFFFFF', borderRadius: 14, borderWidth: 1, borderColor: '#E2E8F0', padding: 14, marginBottom: 10 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, product: { flex: 1, color: '#0F172A', fontWeight: '500', fontSize: 14 }, warning: { color: '#B45309', fontWeight: '500', fontSize: 12 }, safe: { color: '#15803D', fontWeight: '500', fontSize: 12 }, meta: { color: '#64748B', fontSize: 11, marginTop: 6 }, cardActions: { flexDirection: 'row', gap: 8, marginTop: 12 }, cardAction: { height: 34, paddingHorizontal: 14, borderRadius: 9, backgroundColor: '#EFF6FF', justifyContent: 'center' }, cardActionText: { color: '#0057FF', fontSize: 11, fontWeight: '500' }, empty: { padding: 40, alignItems: 'center' }, emptyTitle: { color: '#0F172A', fontWeight: '500', fontSize: 16 }, emptyText: { color: '#64748B', fontSize: 12, marginTop: 6 }, emptyAction: { height: 38, paddingHorizontal: 14, borderRadius: 10, backgroundColor: '#0057FF', justifyContent: 'center', marginTop: 14 }, emptyActionText: { color: '#FFFFFF', fontSize: 12, fontWeight: '500' } });
